"""initial

Revision ID: 84863c84a128
Revises: 
Create Date: 2025-07-04 15:54:50.471041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '84863c84a128'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parceltype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcel',
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('content_value_usd', sa.Float(), nullable=False),
    sa.Column('delivery_cost_rub', sa.Float(), nullable=True),
    sa.Column('parcel_type', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['parcel_type'], ['parceltype.name'], ),
    sa.PrimaryKeyConstraint('parcel_id'),
    sa.UniqueConstraint('parcel_id')
    )

    parceltype_table = table(
        "parceltype",
        column("id", sa.Integer),
        column("name", sa.String),
    )

    # Вставка трёх типов
    op.bulk_insert(parceltype_table, [
        {"id": 1, "name": "clothes"},
        {"id": 2, "name": "electronics"},
        {"id": 3, "name": "miscellaneous"},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel')
    op.drop_table('parceltype')
    # ### end Alembic commands ###
