"""comapny added

Revision ID: 63b7ee17e2d0
Revises: 84863c84a128
Create Date: 2025-07-06 13:51:10.411357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = "63b7ee17e2d0"
down_revision: Union[str, None] = "84863c84a128"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("parcel", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "parcel", "company", ["company_id"], ["id"])
    # ### end Alembic commands ###

    # Вставка 3 компаний
    # bind = op.get_bind()
    # session = Session(bind=bind)

    # session.execute(
    #     sa.insert(sa.table(
    #         'company',
    #         sa.column('name', sa.String),
    #     )),
    #     [
    #         {"name": "DHL Express"},
    #         {"name": "FedEx Logistics"},
    #         {"name": "UPS Shipping"},
    #     ],
    # )
    # session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parcel", type_="foreignkey")
    op.drop_column("parcel", "company_id")
    op.drop_table("company")
    # ### end Alembic commands ###
